### ISSUE TITLE
[Feat] Add website title as "Free Software wing" and our FSW icon beside the title of this website

### ISSUE THREAD

**Issue by fsw-griet** [fsw-griet/fsw#30]
**Is your feature request related to a problem? Please describe.**
Add website title as "Free Software wing"
There is no icon beside the website title but add the icon now

**Describe the solution you'd like**

![image](https://github.com/fsw-griet/fsw/assets/131646904/14d05f79-c1ba-41d1-895d-b2b8c4bd4ac4)

change "Student Body Website" -> "Free Software Wing"

The FSW icon will be available inside the code repo assets folder

Now add this logo as an icon beside the title of the website

**Comment by georgioupanayiotis** [comment]
@fsw-griet assign this to me

**Comment by sujithyadav998** [comment]
hii @fsw-griet could you assign this to me ?

**Comment by Asheklm6** [comment]
@fsw-griet Please can you assign this to me with the label hacktoberfest?

**Comment by Blink29** [comment]
there is no assets folder, assign the issue to me please
